name: build

on: push

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: setup Java version
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: '21'
          check-latest: true
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build and Run Tests
        run: ./gradlew test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}

  push:
    name: Push to sonatype
    runs-on: ubuntu-latest
    steps:
      - name: setup Java version
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: '21'
          check-latest: true
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run grade push task
        run: ./gradlew publishAllPublicationsToCentralPortal
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
